services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DATABASE_ADMIN}"
      MONGO_INITDB_ROOT_PASSWORD: "${DATABASE_ADMIN_PASSWORD}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DATABASE_ADMIN}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DATABASE_ADMIN_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "${DATABASE_URL}"
    depends_on:
      - mongodb

  api:
    build:
      dockerfile: ../docker/DOCKERFILE-API
      context: ./api
    command: npm run dev
    volumes:
      - ./api:/usr/app/
      - api_node_modules:/usr/app/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongodb
    env_file:
      - .env

  frontend:
    build:
      dockerfile: ../docker/DOCKERFILE-FRONTEND
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/usr/app/
      - frontend_node_modules:/usr/app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - mongodb
      - api
    env_file:
      - .env

volumes:
  frontend_node_modules:
  api_node_modules: